version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db_alura
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"